version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3000
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    links:
      - db:db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./test:/app/test
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    volumes:
      - auth-service-db:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doumbiaalmoustapha@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - '5000:80'
    volumes:
      - auth-service-pg:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  auth-service-db:
    driver: local
  auth-service-pg:
    driver: local
  